version: '3.3'
services:
    chartmuseum:
        user: 0:0
        ports:
            - '18080:8080'
        environment:
            - DEBUG=1
            - STORAGE=local
            - STORAGE_LOCAL_ROOTDIR=/charts
        volumes:
            - '$HOME/.local/charts:/charts'
        image: 'chartmuseum/chartmuseum:latest'
